"""
PDF generation utilities for travel itineraries
"""

from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
import streamlit as st


# =========================
# PDF GENERATION
# =========================
def create_pdf_filename(city, country):
    """Create a formatted filename for PDF export"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"itinerary_{city}_{country}_{timestamp}.pdf"


def generate_itinerary_pdf(city, country, weather, season, itinerary_text, city_row, user_input):
    """Generate PDF file from itinerary text with styling"""
    
    pdf_buffer = BytesIO()
    
    try:
        # Create PDF document
        doc = SimpleDocTemplate(
            pdf_buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        # Container for PDF elements
        elements = []
        
        # Define styles
        styles = getSampleStyleSheet()
        
        # Custom title style
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=12,
            alignment=1  # Center alignment
        )
        
        # Custom heading style
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=10,
            spaceBefore=10
        )
        
        # Custom body style
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            alignment=4,  # Justified alignment
            spaceAfter=10
        )
        
        # Add title
        title = Paragraph(
            f"🌍 Itinerary for {city}, {country}",
            title_style
        )
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        # Add metadata table
        metadata = [
            ['Destination', f"{city}, {country}"],
            ['Season', season],
            ['Weather', weather],
            ['Interest', user_input.get('interest', 'N/A')],
            ['Duration', f"{user_input.get('duration', 'N/A')} days"],
            ['Budget Level', user_input.get('budget', 'N/A')],
            ['Generated', datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        ]
        
        metadata_table = Table(metadata, colWidths=[2*inch, 3*inch])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f4f8')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(metadata_table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Add itinerary content
        itinerary_heading = Paragraph("📋 Detailed Itinerary", heading_style)
        elements.append(itinerary_heading)
        elements.append(Spacer(1, 0.1*inch))
        
        # Parse and format itinerary text
        itinerary_paragraphs = itinerary_text.split('\n\n')
        
        for para_text in itinerary_paragraphs:
            if para_text.strip():
                # Handle different text styles
                if para_text.startswith('**'):
                    # Bold text
                    cleaned = para_text.replace('**', '')
                    elements.append(Paragraph(f"<b>{cleaned}</b>", body_style))
                elif para_text.startswith('###'):
                    # Sub-heading
                    cleaned = para_text.replace('###', '').strip()
                    elements.append(Paragraph(f"<b>{cleaned}</b>", heading_style))
                else:
                    # Regular text
                    elements.append(Paragraph(para_text, body_style))
                
                elements.append(Spacer(1, 0.1*inch))
        
        # Add footer with disclaimer
        elements.append(Spacer(1, 0.2*inch))
        footer_text = "This itinerary was generated by AI and is meant as a guide. Please verify all information and consider local conditions before traveling."
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=1
        )
        elements.append(Paragraph(footer_text, footer_style))
        
        # Build PDF
        doc.build(elements)
        
        # Return buffer
        pdf_buffer.seek(0)
        return pdf_buffer
        
    except Exception as e:
        st.error(f"PDF generation error: {e}")
        raise


def format_itinerary_for_pdf(itinerary_text):
    """Format itinerary text for better PDF presentation"""
    lines = itinerary_text.split('\n')
    formatted_lines = []
    
    for line in lines:
        # Keep markdown-style formatting for conversion
        formatted_lines.append(line)
    
    return '\n'.join(formatted_lines)


def export_itinerary_text(city, country, itinerary_text):
    """Export itinerary as plain text file"""
    filename = f"itinerary_{city}_{country}.txt"
    
    content = f"""
TRAVEL ITINERARY
{city}, {country}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
{'='*50}

{itinerary_text}

{'='*50}
This itinerary was AI-generated. Please verify all information.
"""
    
    return content.encode('utf-8'), filename
